from typing import Dict, List, Sequence, Tuple
def _construct_default_factors(
    version_tuples: Sequence[Tuple[int, int]], other_interpreters: Sequence[str]
) -> Dict[str, str]: ...

class PYTHON:
    CPYTHON_VERSION_TUPLES: List[Tuple[int, int]] = ...
    OTHER_PYTHON_INTERPRETERS: List[str] = ...
    DEFAULT_FACTORS: Dict[str, str] = ...
    CURRENT_RELEASE_ENV: str = ...
    QUICKSTART_PY_ENVS: List[str] = ...

class INFO:
    DEFAULT_CONFIG_NAME: str = ...
    IS_WIN: bool = ...

class PIP:
    SHORT_OPTIONS: List[str] = ...
    LONG_OPTIONS: List[str] = ...
    INSTALL_SHORT_OPTIONS_ARGUMENT: List[str] = ...
    INSTALL_LONG_OPTIONS_ARGUMENT: List[str] = ...
